version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - '2181:2181'
    networks:
      - kiwikafka

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CREATE_TOPICS: "incoming-topic:1:1, outgoing-topic:1:1" #topic-name:partitions:replicas
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    networks:
      - kiwikafka

  kiwi:
    image: dmwood/kiwi:latest
    ports:
      - "8081:8080"
    environment:
      KAFKA_BASE_CLIENT_BOOTSTRAPSERVERS: kafka:29092
    networks:
      - kiwikafka
networks:
  kiwikafka: